# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Finite Elemente Methode 1
author: Prof. Dr.-Ing. Steffen Beese
logo: logo.jpeg
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex  
  latex_args: [
    "-synctex=1",
    "-interaction=nonstopmode",
    "-f",
    "-file-line-error",
  ]
  latex_documents:
    targetname: fem_I_skript.tex
  latex_preamble: |
    \usepackage{symbols}  

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/steffenbeese/FEMI_Tutorial  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - dollarmath
    - amsmath

sphinx:
  config:
    language: de
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      tex:
         macros:
          "bm": ["\\boldsymbol{#1}", 1]
          "tbf": ["\\textbf{#1}", 1]
          "tit": ["\\textit{#1}", 1]
          "tsl": ["\\textsl{#1}", 1]
          "tsc": ["\\textsc{#1}", 1]
          "ttt": ["\\texttt{#1}", 1]
          "trm": ["\\textrm{#1}", 1]
          "tsf": ["\\textsf{#1}", 1]
          "tup": ["\\textup{#1}", 1]
          "mbf": ["\\mathbf{#1}", 1]
          "mit": ["\\mathit{#1}", 1]
          "msf": ["\\mathsf{#1}", 1]
          "mrm": ["\\mathrm{#1}", 1]
          "mtt": ["\\mathtt{#1}", 1]
          "dcdot": "\\mathbf{:}"
          "pha": ["#1^{\\alpha}", 1]
          "Pha": ["#1_{\\alpha}", 1]
          "phb": ["#1^{\\beta}", 1]
          "Phb": ["#1_{\\beta}", 1]
          "phu": ["#1^{\\textrm{#2}}", 2]
          "Phu": ["#1_{\\textrm{#2}}", 2]
          "phuR": ["#1^{\\textrm{#2R}}", 2]
          "phaR": ["#1^{\\alpha R}", 1]
          "phbR": ["#1^{\\beta R}", 1]
          "setC": "\\left\\{S,G,L,l\\right\\}"
          "tot": "^{ \\textrm{tot} }"
          "Grad": ["\\textrm{Grad}\\left(#1\\right)", 1]
          "grad": ["\\textrm{grad}\\left(#1\\right)", 1]
          "Div": ["\\textrm{Div} \\left(#1\\right)", 1]
          "div": ["\\textrm{div} \\left(#1\\right)", 1]
          "Lin": "\\textrm{Lin}"
          "intd": "\\ \\textrm{d}"
          "la": "\\, \\leftarrow \\,"
          "dV": "\\; \\textrm{d}V"
          "dViso": "\\; \\textrm{d}V_{\\square}"
          "dA": "\\; \\textrm{d}A"
          "da": "\\; \\textrm{d}a"
          "dx": "\\; \\textrm{ d}x"
          "dxi": "\\; \\textrm{ d}\\xi"
          "d": "\\; \\textrm{ d}"
          "dy": "\\; \\textrm{ d}y"
          "dz": "\\; \\textrm{ d}z"
          "dX": "\\; \\textrm{ d}X"
          "dY": "\\; \\textrm{ d}Y"
          "dZ": "\\; \\textrm{ d}Z"
          "dxi": "\\; \\textrm{ d}\\xi"
          "deta": "\\; \\textrm{ d}\\eta"
          "dzeta": "\\; \\textrm{ d}\\zeta"
          "Ibt": "\\int_{\\mathcal{B}_t}"
          "Ist": "\\int_{\\Gamma_t}"
          "Ibref": "\\int_{\\mathcal{B}\\rs{0}}"
          "Isref": "\\int_{\\Gamma\\rs{0}}"
          "sref": "{\\Gamma\\rs{0}}"
          "Bref": "{\\mathcal{B}\\rs{0}}"
          "Ibiso": "\\int_{\\mathcal{B}_{\\square}}"
          "siso": "{\\Gamma_{\\square}}"
          "Mtd": ["\\left(#1\\right)^{,}", 1]
          "Mtda": ["\\left(#1\\right)^{,}_{\\alpha}", 1]
          "Mtdu": ["\\left(#1\\right)^{,}_{\\textrm{#2}}", 2]
          "td": ["\\dot{#1}", 1]
          "tdd": ["\\ddot{#1}", 1]
          "Pd": ["\\frac{\\partial #1}{\\partial #2}", 2]
          "Dd": ["\\frac{\\text{d }  #1}{\\text{d } #2}", 2]
          "dt": ["#1 ^{\\bullet}", 1]
          "hist": "\\mid_{\\tau=0}^t"
          "rom": ["\\textrm{#1}", 1]
          "rp": ["^{ \\textrm{#1} }", 1]
          "rs": ["_{ \\textrm{#1} }", 1]
          "T": "^{ \\textrm{T} }"
          "mT": "^{ -\\textrm{T} }"
          "dev": "_{ \\textrm{dev} }"
          "sph": "_{ \\textrm{sph} }"
          "hyd": "_{ \\textrm{hyd} }"
          "iso": "_{ \\textrm{iso} }"
          "vol": "_{ \\textrm{vol} }"
          "vM": "_{ \\textrm{vM} }"
          "sym": "_{ \\textrm{sym} }"
          "dil": "_{ \\textrm{dil} }"
          "ln": ["\\textrm{ln}\\left(#1\\right)", 1]
          "uft": "\\mathfrak{\\boldsymbol{u}}"
          "Pext": "\\mathcal{P}\\rp{ext}"
          "Pint": "\\mathcal{P}\\rp{int}"
          "Cg": "\\boldsymbol{C}"
          "detC": "\\det \\Cg"
          "F": "\\bm{F}"
          "s": "\\bm{\\sigma}"
          "ie": "\\rp{e}"
          "ipl": "\\rp{p}"
          "e": "\\varepsilon"
          "eb": "\\bm{\\varepsilon}"
          "ee": ["\\e\\ie", 0]
          "ep": ["\\e\\ipl", 0]
          "E": "\\bm{E}"
          "Ee": ["\\E\\ie", 0]
          "Ep": ["\\E\\ipl", 0]
          "Fe": ["\\bm{\\F}\\ie", 0]
          "Fp": ["\\bm{\\F}\\ipl", 0]
          "Cge": "\\tilde{\\Cg}\\ie"
          "Cgp": ["\\Cg\\ipl", 0]
          "Se": "\\tilde{\\bm{S}}\\ie"
          "Me": "\\tilde{\\bm{M}}\\ie"
          "Lp": "\\tilde{\\bm{L}}\\ipl"
          "Dp": "\\tilde{\\bm{D}}\\ipl"
          "sw": "\\rs{sw}"
          "IV": "\\bm{Y}"
          "iv": "Y"
          "psiCap": "\\psi\\rs{cap}"
          "psiCapcv": "\\psi\\rs{cap-cv}"
          "psiAd": "\\psi\\rs{ad}"
          "pCap": "p\\rs{cap}"
          "pCapcv": "p\\rs{cap-cv}"
          
    bibtex_bibfiles:
      - references.bib
    bibtex_reference_style: author_year
    latex_elements:
      preamble: |
        \usepackage{symbols}        

execute:
  execute_notebooks: cache
  run_in_temp: true